<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="43422" started-at="2020-03-30T00:54:24 IST" finished-at="2020-03-30T00:55:07 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="43422" started-at="2020-03-30T00:54:24 IST" finished-at="2020-03-30T00:55:07 IST">
      <class name="jenkins.selenium_testng_jenkins.AppTest">
        <test-method status="PASS" signature="shouldAnswerWithTrue()[pri:0, instance:jenkins.selenium_testng_jenkins.AppTest@1d29cf23]" name="shouldAnswerWithTrue" duration-ms="11" started-at="2020-03-30T00:54:27 IST" finished-at="2020-03-30T00:54:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shouldAnswerWithTrue -->
      </class> <!-- jenkins.selenium_testng_jenkins.AppTest -->
      <class name="urllogin.Login">
        <test-method status="PASS" signature="beforetest()[pri:0, instance:urllogin.Login@27a5f880]" name="beforetest" is-config="true" duration-ms="3266" started-at="2020-03-30T00:54:24 IST" finished-at="2020-03-30T00:54:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforetest -->
        <test-method status="PASS" signature="login()[pri:0, instance:urllogin.Login@27a5f880]" name="login" duration-ms="28782" started-at="2020-03-30T00:54:27 IST" finished-at="2020-03-30T00:54:56 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="loginfail()[pri:0, instance:urllogin.Login@27a5f880]" name="loginfail" duration-ms="10987" started-at="2020-03-30T00:54:56 IST" finished-at="2020-03-30T00:55:07 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Home | Let's Kode It] but found [Let's Kode It]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Home | Let's Kode It] but found [Let's Kode It]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at urllogin.Login.loginfail(Login.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginfail -->
        <test-method status="PASS" signature="aftertest()[pri:0, instance:urllogin.Login@27a5f880]" name="aftertest" is-config="true" duration-ms="281" started-at="2020-03-30T00:55:07 IST" finished-at="2020-03-30T00:55:07 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftertest -->
      </class> <!-- urllogin.Login -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
